AllCops:
  TargetRubyVersion: 2.7

inherit_from:
  - https://dbdrive.github.io/triebwerk/rubocop_common.yml

RSpec/NestedGroups:
  Exclude:
    - 'spec/lib/thingsboard/api/base_spec.rb'
    - 'spec/lib/thingsboard/device_api/base_spec.rb'