plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'utils/**/*'
  SuggestExtensions: false

########## BUNDLER
Bundler/OrderedGems:
  Enabled: false

########## FACTORY BOT

FactoryBot/SyntaxMethods:
  Enabled: false

########## LAYOUT
Layout/DotPosition:
  EnforcedStyle: leading

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/ExtraSpacing:
  # We use extra spacing deliberately to make table-like information more
  # readable. This cop is not smart enough to always recognize the intent.
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  AutoCorrect: false
  Max: 120
  AllowedPatterns: ['\A\s*#']

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceBeforeBrackets:
  # We are using a lot of method calls without parentheses and use an array as
  # an argument. Those calls would be broken
  Enabled: false

########## LINT
# Disabled as a suggestion from https://github.com/rubocop-hq/rubocop/issues/4222
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/EmptyWhen:
  Enabled: false

Lint/DuplicateElsifCondition:
  Enabled: false

Lint/DuplicateRequire:
  Enabled: false

Lint/DuplicateRescueException:
  Enabled: false

Lint/EmptyConditionalBody:
  Enabled: false

Lint/EmptyFile:
  Enabled: false

Lint/FloatComparison:
  Enabled: false

Lint/HashCompareByIdentity:
  Enabled: false

Lint/IdentityComparison:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Lint/NoReturnInBeginEndBlocks:
  Enabled: false

Lint/OutOfRangeRegexpRef:
  Enabled: false

Lint/RedundantSafeNavigation:
  Enabled: false

Lint/SelfAssignment:
  Enabled: false

Lint/SymbolConversion:
  # Both "string_#{interpolation}".to_sym and :"string_#{interpolation}"" have their place.
  Enabled: false

Lint/TopLevelReturnWithArgument:
  Enabled: false

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: false

Lint/UnreachableLoop:
  Enabled: false

Lint/UselessMethodDefinition:
  Enabled: false

Lint/UselessTimes:
  Enabled: false

########## METRICS
Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

########## NAMING
Naming/InclusiveLanguage:
  Enabled: false
  Severity: info

Naming/PredicatePrefix:
  # Renaming `has_something?` to `something?` obfuscates whether it is a "is-a" or
  # a "has-a" relationship.
  Enabled: false

Naming/PredicateMethod:
  # Too many false positives in our code base.
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Exclude:
    - 'app/controllers/**/*'
    - 'spec/controllers/**/*'

########## STYLE
Style/Documentation:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: empty

Style/FrozenStringLiteralComment:
  EnforcedStyle: always
  Exclude:
    - 'spec/**/*'

Style/IfUnlessModifier:
  Enabled: false

# Requires Ruby 3.1
Style/NestedFileDirname:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/SymbolArray:
  EnforcedStyle: brackets

Style/NegatedIf:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/EmptyStringInsideInterpolation:
  Enabled: false

Style/CollectionQuerying:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/RedundantCondition:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/FloatDivision:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/ClassEqualityComparison:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/HashLikeCase:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/RedundantArgument:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/RedundantSelfAssignment:
  Enabled: false

Style/SignalException:
  # When running rubocop with autocorrect (-a)
  # this changes our tests for failing operations
  #   it { is_expected.to fail.with_error(:foobar) }
  # to
  #   it { is_expected.to raise.with_error(:foobar) }
  #
  # which of course does not work ...
  Exclude:
    - '**/*_spec.rb'
    - 'spec/support/*.rb'

Style/SingleArgumentDig:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/YodaExpression:
  Enabled: false

# -----------------------------------------------------------------------------
# RuboCop RSpec
RSpec/AnyInstance:
  Enabled: false

RSpec/BeEmpty:
  Enabled: false

RSpec/BeEql:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/EmptyLineAfterFinalLet:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ImplicitSubject:
  EnforcedStyle: single_statement_only

RSpec/IndexedLet:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MatchArray:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false

RSpec/SortMetadata:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/VariableName:
  EnforcedStyle: snake_case
  AllowedPatterns:
    - '^X-'
    - 'Authorization'

# -----------------------------------------------------------------------------
# RuboCop FactoryBot
FactoryBot/ExcessiveCreateList:
  # We know what we're doing.
  Enabled: false
